import { Img } from "./Img";
import { Input } from "./Input";
import { Button } from "./Button";
import { Text } from "./Text";
import { Heading } from "./Heading";
import { Slider } from "./Slider";
import { RatingBar } from "./RatingBar";
import { CheckBox } from "./CheckBox";
import { ReactTable } from "./ReactTable";
import { SelectBox } from "./SelectBox";
export { Img, Input, Button, Text, Heading, Slider, RatingBar, CheckBox, ReactTable, SelectBox };
