/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/dv7LbVv0PPe
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"

export function reportcard() {
  return (
    <Card key="1" className="w-full max-w-md">
      <CardHeader className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <FileIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
          <CardTitle>Weekly Report</CardTitle>
        </div>
        <div className="rounded-full bg-green-100 px-3 py-1 text-xs font-medium text-green-600 dark:bg-green-900 dark:text-green-400">
          Approved
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Avatar>
              <AvatarImage alt="User Avatar" src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div>
              <p className="text-sm font-medium">John Doe</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">john@example.com</p>
            </div>
          </div>
          <p className="text-sm text-gray-500 dark:text-gray-400">May 14, 2024</p>
        </div>
        <div className="space-y-2">
          <p>
            This week's report includes a summary of the key metrics, highlights from the past week, and plans for the
            upcoming week.
          </p>
          <img
            alt="Report Image"
            className="rounded-lg"
            height="200"
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/200",
              objectFit: "cover",
            }}
            width="400"
          />
        </div>
      </CardContent>
      <CardFooter className="flex justify-center gap-2">
        <Button variant="outline">Decline</Button>
        <Button>Accept</Button>
      </CardFooter>
    </Card>
  )
}

function FileIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
    </svg>
  )
}
